name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  swift-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Build (release)
        run: swift build -c release

